//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeltecDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int ContactId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string HomeAddress { get; set; }
        public string MobileNo { get; set; }
        public string LandlineNo { get; set; }
        public string EmailId { get; set; }
        public string SkypeId { get; set; }
        public string SlackId { get; set; }
        public string LinkedlnId { get; set; }
        public string OfficeAddress { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
    }
}
