//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeltecDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienceDetail
    {
        public int ExperienceId { get; set; }
        public int EmployeeId { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public string Experience { get; set; }
        public string Designation { get; set; }
        public string CurrentCompany { get; set; }
        public string Sector { get; set; }
        public string PreviousCompany { get; set; }
    }
}
