//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeltecDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherDetail
    {
        public int OtherId { get; set; }
        public string DrivingLicenceNo { get; set; }
        public string AadharNo { get; set; }
    }
}
