//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeltecDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Father_HusbandName { get; set; }
        public string Gender { get; set; }
        public string MaritialStatus { get; set; }
        public string Citizenship { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public Nullable<int> CasteId { get; set; }
        public Nullable<int> SubCasteId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual CasteMaster CasteMaster { get; set; }
        public virtual SubCasteMaster SubCasteMaster { get; set; }
    }
}
