//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeltecDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultData
    {
        public int Resultid { get; set; }
        public Nullable<int> ExId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Grade { get; set; }
    }
}
